import { NextRequest, NextResponse } from 'next/server'
import { productsDb, initializeDatabase } from '@/src/lib/database'
import { CreateProductRequest, ApiResponse, PaginatedResponse } from '@/src/lib/types'

// Shopify integration
const USE_SHOPIFY = process.env.NEXT_PUBLIC_USE_SHOPIFY === 'true'

// Initialize database on first request
let initialized = false

async function ensureInitialized() {
  if (!initialized) {
    await initializeDatabase()
    initialized = true
  }
}

export async function GET(request: NextRequest) {
  try {
    // If Shopify is enabled, try Shopify API first
    if (USE_SHOPIFY) {
      try {
        const shopifyUrl = new URL('/api/shopify/products', request.url)
        shopifyUrl.search = new URL(request.url).search
        
        const shopifyResponse = await fetch(shopifyUrl.toString())
        const shopifyData = await shopifyResponse.json()
        
        // If Shopify returns success, use it
        if (shopifyResponse.ok && shopifyData.success) {
          return NextResponse.json(shopifyData, { status: shopifyResponse.status })
        }
        
        // If Shopify fails, log error and fall back to mock data
        console.warn('Shopify API unavailable, falling back to mock data:', shopifyData.error)
      } catch (shopifyError) {
        console.warn('Shopify connection failed, falling back to mock data:', shopifyError)
      }
    }

    // Use mock data (either Shopify disabled or Shopify failed)
    await ensureInitialized()
    
    const { searchParams } = new URL(request.url)
    const page = parseInt(searchParams.get('page') || '1')
    const limit = parseInt(searchParams.get('limit') || '12')
    const category = searchParams.get('category')
    const tag = searchParams.get('tag')
    const search = searchParams.get('search')

    let products = await productsDb.findAll()

    // Apply filters
    if (category) {
      products = products.filter(p => p.category.toLowerCase() === category.toLowerCase())
    }

    if (tag) {
      products = products.filter(p => p.tags.some(t => t.toLowerCase() === tag.toLowerCase()))
    }

    if (search) {
      const searchLower = search.toLowerCase()
      products = products.filter(p => 
        p.title.toLowerCase().includes(searchLower) ||
        p.description.toLowerCase().includes(searchLower) ||
        p.tags.some(t => t.toLowerCase().includes(searchLower))
      )
    }

    // Paginate results
    const total = products.length
    const totalPages = Math.ceil(total / limit)
    const offset = (page - 1) * limit
    const paginatedProducts = products.slice(offset, offset + limit)

    const response: PaginatedResponse<typeof paginatedProducts[0]> = {
      success: true,
      data: paginatedProducts,
      pagination: {
        page,
        limit,
        total,
        totalPages
      }
    }

    return NextResponse.json(response)
  } catch (error) {
    console.error('Error fetching products:', error)
    const response: ApiResponse = {
      success: false,
      error: 'Failed to fetch products'
    }
    return NextResponse.json(response, { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  try {
    await ensureInitialized()
    
    const body: CreateProductRequest = await request.json()
    
    // Validate required fields
    if (!body.title || !body.description || !body.price) {
      const response: ApiResponse = {
        success: false,
        error: 'Missing required fields: title, description, price'
      }
      return NextResponse.json(response, { status: 400 })
    }

    // Generate handle from title
    const handle = body.title
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .trim()

    // Generate SKU if not provided
    const sku = `${body.category?.substring(0, 2).toUpperCase() || 'PR'}-${Date.now().toString().slice(-6)}`

    const product = await productsDb.create({
      id: '', // Will be generated by database
      title: body.title,
      handle,
      description: body.description,
      story: body.story || '',
      price: body.price,
      compareAtPrice: body.compareAtPrice,
      images: body.images || [],
      category: body.category || 'General',
      subcategory: body.subcategory,
      tags: body.tags || [],
      sku,
      inStock: true,
      inventory: body.inventory || 0,
      sizes: body.sizes || [],
      colors: body.colors || [],
      features: body.features || [],
      designer: body.designer || '',
      designerQuote: body.designerQuote || '',
      sustainabilityInfo: body.sustainabilityInfo || '',
      editorial: body.editorial || {
        title: '',
        content: '',
        image: ''
      },
      createdAt: '',
      updatedAt: ''
    })

    const response: ApiResponse<typeof product> = {
      success: true,
      data: product,
      message: 'Product created successfully'
    }

    return NextResponse.json(response, { status: 201 })
  } catch (error) {
    console.error('Error creating product:', error)
    const response: ApiResponse = {
      success: false,
      error: 'Failed to create product'
    }
    return NextResponse.json(response, { status: 500 })
  }
}