import { NextRequest, NextResponse } from 'next/server'
// @ts-ignore
import { productsDb, initializeDatabase } from '@/src/lib/database'
// @ts-ignore
import { CreateProductRequest, ApiResponse, PaginatedResponse } from '@/src/lib/types'
import { getAllProducts, getAllProductsByCategory, getProductsByMiniCollection } from '@/data/tiktok-products'

export const dynamic = 'force-dynamic'

// Shopify integration
const USE_SHOPIFY = process.env.NEXT_PUBLIC_USE_SHOPIFY === 'true'

// Initialize database on first request
let initialized = false

async function ensureInitialized() {
  if (!initialized) {
    await initializeDatabase()
    initialized = true
  }
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const page = parseInt(searchParams.get('page') || '1')
    const limit = parseInt(searchParams.get('limit') || '12')
    const category = searchParams.get('category')
    const collection = searchParams.get('collection')
    const tag = searchParams.get('tag')
    const search = searchParams.get('search')
    const source = searchParams.get('source') || 'all' // all, tiktok, shopify

    let products: any[] = []

    // Fetch TikTok products if requested
    if (source === 'tiktok' || source === 'all') {
      if (collection) {
        products.push(...getProductsByMiniCollection(collection as any))
      } else if (category) {
        products.push(...getAllProductsByCategory(category as any))
      } else {
        products.push(...getAllProducts())
      }
    }

    // Fetch Shopify products if requested
    if ((source === 'shopify' || source === 'all') && USE_SHOPIFY) {
      try {
        await ensureInitialized()
        const shopifyProducts = await productsDb.findAll()
        
        // Filter Shopify products
        let filtered = shopifyProducts
        if (category) {
          filtered = filtered.filter(p => p.category.toLowerCase() === category.toLowerCase())
        }
        if (tag) {
          filtered = filtered.filter(p => p.tags.some(t => t.toLowerCase() === tag.toLowerCase()))
        }
        
        products.push(...filtered)
      } catch (error) {
        console.warn('Failed to fetch Shopify products:', error)
      }
    }

    // Apply additional filters
    if (search) {
      const searchLower = search.toLowerCase()
      products = products.filter(p => 
        (p.title || p.name || '').toLowerCase().includes(searchLower) ||
        (p.description || '').toLowerCase().includes(searchLower) ||
        (p.tags || []).some((t: string) => t.toLowerCase().includes(searchLower))
      )
    }

    // Remove duplicates by SKU/ID
    const seen = new Set()
    products = products.filter(p => {
      const key = p.sku || p.id
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })

    // Paginate results
    const total = products.length
    const totalPages = Math.ceil(total / limit)
    const offset = (page - 1) * limit
    const paginatedProducts = products.slice(offset, offset + limit)

    const response: any = {
      success: true,
      data: paginatedProducts,
      pagination: {
        page,
        limit,
        total,
        totalPages
      },
      filters: {
        category: category || null,
        collection: collection || null,
        source,
        search: search || null
      }
    }

    return NextResponse.json(response)
  } catch (error) {
    console.error('Error fetching products:', error)
    const response: ApiResponse = {
      success: false,
      error: 'Failed to fetch products'
    }
    return NextResponse.json(response, { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  try {
    await ensureInitialized()
    
    const body: CreateProductRequest = await request.json()
    
    // Validate required fields
    if (!body.title || !body.description || !body.price) {
      const response: ApiResponse = {
        success: false,
        error: 'Missing required fields: title, description, price'
      }
      return NextResponse.json(response, { status: 400 })
    }

    // Generate handle from title
    const handle = body.title
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .trim()

    // Generate SKU if not provided
    const sku = `${body.category?.substring(0, 2).toUpperCase() || 'PR'}-${Date.now().toString().slice(-6)}`

    const product = await productsDb.create({
      id: '', // Will be generated by database
      title: body.title,
      handle,
      description: body.description,
      story: body.story || '',
      price: body.price,
      compareAtPrice: body.compareAtPrice,
      images: body.images || [],
      category: body.category || 'General',
      subcategory: body.subcategory,
      tags: body.tags || [],
      sku,
      inStock: true,
      inventory: body.inventory || 0,
      sizes: body.sizes || [],
      colors: body.colors || [],
      features: body.features || [],
      designer: body.designer || '',
      designerQuote: body.designerQuote || '',
      sustainabilityInfo: body.sustainabilityInfo || '',
      editorial: body.editorial || {
        title: '',
        content: '',
        image: ''
      },
      createdAt: '',
      updatedAt: ''
    })

    const response: ApiResponse<any> = {
      success: true,
      data: product,
      message: 'Product created successfully'
    }

    return NextResponse.json(response, { status: 201 })
  } catch (error) {
    console.error('Error creating product:', error)
    const response: ApiResponse = {
      success: false,
      error: 'Failed to create product'
    }
    return NextResponse.json(response, { status: 500 })
  }
}
