import { NextRequest, NextResponse } from 'next/server'
import { collectionsDb, productsDb, initializeDatabase } from '@/lib/database'
import { ApiResponse, Collection } from '@/lib/types'

export const dynamic = 'force-dynamic'
export const revalidate = 0
export const dynamic = 'force-dynamic'

// Initialize database on first request
let initialized = false

async function ensureInitialized() {
  if (!initialized) {
    await initializeDatabase()
    initialized = true
  }
}

export async function GET(request: NextRequest) {
  try {
    await ensureInitialized()
    
    const { searchParams } = new URL(request.url)
    const includeProducts = searchParams.get('includeProducts') === 'true'

    const collections = await collectionsDb.findAll()

    if (includeProducts) {
      // Populate collections with actual product data
      const collectionsWithProducts = await Promise.all(
        collections.map(async (collection) => {
          const products = await Promise.all(
            collection.products.map(productId => productsDb.findById(productId))
          )
          
          return {
            ...collection,
            products: products.filter(Boolean) // Remove null products
          }
        })
      )

      const response: ApiResponse<typeof collectionsWithProducts> = {
        success: true,
        data: collectionsWithProducts
      }

      return NextResponse.json(response)
    }

    const response: ApiResponse<Collection[]> = {
      success: true,
      data: collections
    }

    return NextResponse.json(response)
  } catch (error) {
    console.error('Error fetching collections:', error)
    
    // Provide fallback collections when database fails
    const fallbackCollections = [
      {
        id: "boards",
        title: "Boards",
        handle: "boards",
        description: "Surf and skate boards for every level",
        image: "/images/ocean-bw-5.jpg",
        products: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      },
      {
        id: "apparel", 
        title: "Apparel",
        handle: "apparel",
        description: "Clothing and accessories for your active lifestyle",
        image: "/images/lifestyle/palm-trees-sky-2.jpg",
        products: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      },
      {
        id: "self-care",
        title: "Self Care",
        handle: "self-care",
        description: "Products to help you look and feel your best",
        image: "/images/brand/highway-lights-1.jpg",
        products: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      }
    ]

    const response: ApiResponse<typeof fallbackCollections> = {
      success: true,
      data: fallbackCollections,
      message: 'Using fallback collections data'
    }
    
    return NextResponse.json(response)
  }
}

export async function POST(request: NextRequest) {
  try {
    await ensureInitialized()
    
    const body = await request.json()
    const { title, description, image, products = [] } = body

    if (!title || !description) {
      const response: ApiResponse = {
        success: false,
        error: 'Missing required fields: title, description'
      }
      return NextResponse.json(response, { status: 400 })
    }

    // Generate handle from title
    const handle = title
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .trim()

    const collection = await collectionsDb.create({
      id: '', // Will be generated by database
      title,
      handle,
      description,
      image: image || '',
      products,
      createdAt: '',
      updatedAt: ''
    })

    const response: ApiResponse<Collection> = {
      success: true,
      data: collection,
      message: 'Collection created successfully'
    }

    return NextResponse.json(response, { status: 201 })
  } catch (error) {
    console.error('Error creating collection:', error)
    const response: ApiResponse = {
      success: false,
      error: 'Failed to create collection'
    }
    return NextResponse.json(response, { status: 500 })
  }
}